name: GameCI 🎮
on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
